version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python monitor.py
    depends_on:
      - db
  db:
    image: postgres:12.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: monitor_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
